eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

server: 
  port: 0
spring: 
  application: 
    name: order-service
  cloud: 
    config: 
      fail-fast: true
      uri: "${CONFIG_SERVER_URI:http://localhost:7777}"
  datasource: 
    continue-on-error: true
    driver-class-name: org.h2.Driver
    password: root
    url: "jdbc:h2:file:~/cqrs;AUTO_SERVER=true"
    username: root
  h2: 
    console: 
      enabled: true
      settings: 
        web-allow-others: true
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: 
      ddl-auto: update
